.DEFAULT_GOAL := all

all: calculator.py
	@python3 calculator.py 
pack:
	#prikaz pro udelani zipu
clean:
	rm -r "__pycache__"
test:
	@python3 tdd.py
doc:
	#prikaz pro generovani dokumentace
run:
	@python3	calculator.py
profile:
	@python3 stddev.py #stddev.py nahradit cestou k souboru pro vypocet smerodatne odchylky s testovacim vstupem





